# Generated by Django 4.0.4 on 2023-06-23 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
