# Generated by Django 4.0.4 on 2023-06-24 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0003_alter_records_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
