# Generated by Django 4.2.2 on 2023-06-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0008_user_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_created',
        ),
    ]
